---
galaxy_info:
  description: "Ansible role 'iio-niri-lisgd'"

  # Platforms is a list of platforms, and each platform has a name and a list of versions.
  platforms:
    - name: "ArchLinux"
      versions:
        - "all"

# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
dependencies:
  - role: "arcfg.hardware.iio_niri"
  - role: "arcfg.hardware.lisgd"
